[package]
name = 'note'
version = '0.1.0'
edition.workspace = true

[dependencies]
anyhow = '1'
pulldown-cmark = { version = '0.13.0', default-features = false, features = ['simd'] }
serde_json = '1'
serde_yaml = '0.9'
