[package]
name = 'image-core'
version = '0.1.0'
edition.workspace = true

[dependencies]
image = '0.25.9'
serde = { version = '1', features = ['derive'] }
webp = '0.3'

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = '0.10'
core-graphics = '0.24'
foreign-types = '0.5'
