[package]
name = 'app-storage'
version = '0.1.0'
edition.workspace = true

[dependencies]
anyhow = '1'
include_dir = '0.7.4'
rusqlite = { version = '0.31', features = ['bundled'] }
serde = { version = '1', features = ['derive'] }
sqlite-vec = '0.1.6'
